name: CI/CD Workflow

on:
  pull_request:
    branches:
      - "*"

  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run: npm install

      - name: Lint du fichier index.js
        run: npm run lint-index

      - name: Lint du fichier test.js
        run: npm run lint-test

      - name: Lint du fichier Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

  jest-test:
    name: Test avec jest et supertest
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Installation des dépendances JavaScript
        run: npm install

      - name: Test
        run: npm run test

  docker-test:
    name: Build Dockerfile
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main' || (github.event_name == 'push' && github.ref_type == 'tag')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de docker
        uses: docker/setup-buildx-action@v3

      - name: Build youpidok/random-number
        run: docker build --rm -t youpidok/random-number .

      - name: Run youpidok/random-number
        run: docker run --name random-number -p 3000:3000 -d youpidok/random-number

  deploy-image-latest:
    name: Push youpidok/random-number:latest
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || (github.event_name == 'push' && github.ref_type == 'tag')
    needs:
      - lint
      - jest-test
      - docker-test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de docker
        uses: docker/setup-buildx-action@v3

      - name: Build youpidok/random-number:latest
        run: docker build --rm -t youpidok/random-number:latest .

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: youpidok
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push youpidok/random-number:latest
        run: docker push youpidok/random-number:latest

  deploy-image-tag:
    name: Push youpidok/random-number:tag
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref_type == 'tag'
    needs:
      - lint
      - jest-test
      - docker-test
      - deploy-image-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de docker
        uses: docker/setup-buildx-action@v3

      - name: Build youpidok/random-number:${{github.ref_name}}
        run: docker build --rm -t youpidok/random-number:${{github.ref_name}} .

      - name: Connexion à Docker Hub
        uses: docker/login-action@v3
        with:
          username: youpidok
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag youpidok/random-number:${{github.ref_name}}
        run: docker tag youpidok/random-number:${{github.ref_name}} youpidok/random-number:${{github.ref_name}}

      - name: Push youpidok/random-number:${{github.ref_name}}
        run: docker push youpidok/random-number:${{github.ref_name}}

      - name: Génération des notes de la release ${{github.ref_name}}
        uses: release-drafter/release-drafter@v5
        with:
          name: v${{github.ref_name}}
          tag: ${{github.ref_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB_TOKEN }}